# -*- coding: utf-8 -*-
"""model_deployment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12-ZJ2zT1IgjnvsvWDJmREhNQ2dJAcIS5
"""


import streamlit as st
import pandas as pd
import numpy as np
import pickle
from sklearn.ensemble import RandomForestClassifier

random_forest = RandomForestClassifier()

filename = 'final_model.pkl'
pickle.dump(random_forest, open(filename, 'wb'))
loaded_model = pickle.load(open("final_model.pkl",'rb'))

df = pd.read_csv("H:\DS_Project-2\Clustered_Customer_Data.csv")

y = df[['cluster_labels']]
y = np.ravel(y)
drop_columns = ['cluster_labels','Unnamed: 0']
X = df.drop(columns = drop_columns, axis=1 )

st.title('Customer Personality Analysis')
st.subheader('User_Input_Values')

st.sidebar.header("Education Details")
st.sidebar.write("Graduation - 2")
st.sidebar.write("PhD - 4")
st.sidebar.write("Master - 3")
st.sidebar.write("Basic - 1")
st.sidebar.write("2n Cycle - 0")

st.sidebar.header("Marital_Status")
st.sidebar.write("Single - 4") 
st.sidebar.write("Together - 5")
st.sidebar.write("Married - 3") 
st.sidebar.write("Divorced - 2")
st.sidebar.write("Widow - 6")
st.sidebar.write("Alone - 1")
st.sidebar.write("Absurd - 0")
st.sidebar.write("YOLO - 7")

with st.form('my_form'):
  Education = st.number_input(label='Education',step=1)
  Marital_Status = st.number_input(label='Marital_Status',step=1)
  Income	= st.number_input(label='Income',step=1, format='%.2f')
  Kidhome	= st.number_input(label='Kidhome',step=1)
  Teenhome = st.number_input(label='Teenhome',step=1)
  Recency	= st.number_input(label='Recency',step=1)
  Complain	= st.number_input(label='Complain',step=1)
  Age	= st.number_input(label='Age',step=1)
  Total_Amount	= st.number_input(label='Total_Amount',step=1)
  Total_Purchases	= st.number_input(label='Total_Purchases',step=1)
  Total_Accepted_Complains = st.number_input(label='Total_Accepted_Complains',step=0.1)

  submitted = st.form_submit_button('Submit')

# Convert input data to DataFrame
input_data = [[Education,	Marital_Status,	Income,	Kidhome,	Teenhome,	Recency,	Complain,	Age,	Total_Amount,	Total_Purchases,	Total_Accepted_Complains]]
input_df = pd.DataFrame(input_data, columns=['Education', 'Marital_Status', 'Income', 'Kidhome', 'Teenhome', 'Recency', 'Complain', 'Age', 'Total_Amount', 'Total_Purchases', 'Total_Accepted_Complains'])

# Display predictions
if submitted:
    loaded_model.fit(X,y)
    prediction = loaded_model.predict(input_df)
    st.write('Predicted Cluster Label:', prediction[0])

